OctoPrint/octoprint-docker

- Dockerfile
There is a deprecation warning.
>Starting the server via "octoprint" is deprecated, please use "octoprint serve" from now on.
> Starting the server via "octoprint" is deprecated

- Dockerfile
The active home directory for the user octoprint is /home/octoprint vs
/user/octoprint
When /home/octoprint/.octoprint is exposed as a volume, it has to be
the last thing exposed so that permissions can be set correctly and
data can be copied first.
> Corrected VOLUME instruction && permissions fix

- README.md
The README lists a docker run command and provides a `-v` argument but no required list of volumes to mount. If copy/pasting this fails with a less than intuitive error. 
```
$ docker run -d -v --device /dev/ttyACM0:/dev/ttyACM0 -p 5000:5000 --name octoprint octoprint/octoprint
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```
I just updated the docker run command in the README to use the volume mentioned in the docker-compose.yml
> update README docker run command to provide a volume list 

- .gitignore
- .travis.yml
- .travis/install.sh
- CONTRIBUTING.md
- Dockerfile
- Makefile
- config.env
- docker-compose.yml
- docker-entrypoint.sh
- version.sh
There are a lot of changes here. I tried to make the history of each commit a step by step of what is changing and why, so I'll just summarize the changes in full here.  I have also added documentation about configuring the build in a new `CONTRIBUTING.md` file, so be sure to read that as part of the PR.
I tried to break this up into smaller chunks, but there wasn't really a way to do this without going all in, and this was the first true stopping point. 
PR's to follow this will do change the final base image to create a much _much_ smaller final image, and will also create multi-arch builds by default, including appropriate versions of ffmpeg (see #18 ).
- used multi staged builds for faster build and smaller final images (eliminates the need to do things like clean sources and tmp dirs …
> Multi stage dynamically configurable build

- Dockerfile
- Makefile
Limited to the architecture platform the python base image supports, so only able to add armv7 at this time.
closes #6
> add support and builds for armhf

- Dockerfile
remove make and g++ and added build-essential
(make and g++ are included in build-essential)
closes #33
> update build stage package installs

- Dockerfile
- Makefile
- env.mk
- updates to use `OctoPrint/OctoPrint` instead of `foosel/OctoPrint`
- add version tagging to Makefile
- will assign `latest` tag if no IMG_TAG is used or in env
- will pass the latest stable release tag to docker unless overridden by command/env
> Update octoprint src path

- .github/workflows/build-latest.yml
- Dockerfile
Switched `compiler` stage to use `pip install .` instead of `python setup.py install`.  This matches the octoprint/octoprint ci build flow, and should produce consistent build success/fails as upstream, and not cause PR's to fail even when they are building stable octoprint tags.
Fixes #39
> Fix buildx fail

- README.md
Updating README to include current state of affairs (challenges of running OctoPrint in docker), and a warning/recommendation to use native install or octopi install unless you have strong docker knowledge.
> update README state of octoprint/docker image

- .github/workflows/build.yml
- .github/workflows/octoprint-release.yml
- Dockerfile.camera
- Makefile
- camera/Dockerfile.camera
- camera/etc/haproxy/haproxy.cfg
- camera/etc/services.d/haproxy/run
- camera/etc/services.d/mjpg-streamer/run
- uses s6 process supervisor
- uses the default octoprint image of the same version as the base image
- currently forces `/dev/video0` for webcam input 
- will require the use of mapping your video drive to `/dev/video0` until we get the `CAMERA_DEV` var supported. Ex...( `-v /dev/video1:/dev/video0`)
- uses non-privileged port of `8888` as the haproxy frontend
- supports `arm64,amd64,armhf` architectures (same as the base image)
- only available in `slim-buster` for now (same as the base image)
- builds 3 tags automatically on releases of OctoPrint, by running the Manual Dispatch action on this repo, or on pushes to master
- `X-camera`, `X.Y-camera`, `X.Y.Z-camera`
- X.Y.Z will be equal to the most recent OctoPrint Release or prerelease
closes #47
> Add camera image variant

- docker-compose.yml
docker-compose v3.x is designed to accommodate docker swarm mode. As most people will be using this on a single node lets use v2.4 instead so that we can still constrain resources and avoid a torrent of support issues when people lookup the file format.
> Switch docker-compose to v2.4 to avoid swarm questions

- .github/workflows/build.yml
The filtering on the build workflow was always evaluating to `true` because it wasn't doing an actual evaluation of the filter key values.
> Fix build filtering

- README.md
The current docs have `CAMERA_DEV` listed twice, and looks like the real column value was accidentally put in the second column.  This fixes that so the table has the correct `MJPEG_STREAMER_INPUT` in the config name column, and the correct default setting in the value column.
> fix variable names in config docs

- .gitignore
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
- root/etc/cont-init.d/01-mjpeg-streamer-config
- root/etc/cont-init.d/01-mjpg-streamer-config
- root/etc/services.d/mjpg-streamer/run
**BREAKING CHANGES** (mjpg-streamer will no longer be started by default, user will need to pass `ENABLE_MJPG_STREAMER` to start this service with the container)
- deprecated `MJPEG_STREAMER_INPUT` in favor of `MJPG_STREAMER_INPUT`
- makes usage of `mjpg-streamer` consistent (changed all `mjpeg` usages to `mjpg`
- makes the mjpg-streamer service optional (defaults to false) 
closes #84
> Feature optional mjpeg streamer startup

- Dockerfile
Change pip installation to the recommended install method, and change to using `/octoprint` as a full (non-symlink) directory by passing a `--basedir /octoprint` option to the octoprint command.
> change pip install and octoprint basedir

- .github/filters.yml
- .github/workflows/octoprint-release.yml
- removes use of _files in filter names since that is now used in dory/paths-filter
- removed `if` logic of `filters` job since that is what the `on` is for
- note: this was previously programmed with incorrect logic, basically causing the trigger for `release_main` to never run on release or push to master
> Fix image deploy workflow

- .github/workflows/build.yml
- .github/workflows/manual-repo-dispatch.yml
- .github/workflows/octoprint-release.yml
- Dockerfile
- Makefile
- minimal/Dockerfile
- eliminates usage of now deprecated `set-env`. Closes #99 
- migrates to using new official docker actions 
- now builds all image tags in a single build step instead of using a matrix.  This means image digests for each arch will match for the tags created.
> Update usage set env in workflows

- docker-compose.yml
The video spacing is now consistent with ttyACM0 spacing.
> Add consistent spacing for docker-compose devices.

- .github/workflows/octoprint-release.yml
This should resolve the warning about 'no `before` field in PUSH payload event that we're seeing in some runs of the release workflow.  ([example of warning](https://github.com/OctoPrint/octoprint-docker/actions/runs/403154220))
Per the release notes for 2.6.0 for paths-filter: https://github.com/dorny/paths-filter/releases/tag/v2.6.0
> update action dorny/paths-filter to 2.6.0

- Dockerfile
- README.md
- compose.test.yml
- docker-compose.yml
- root/etc/services.d/octoprint/run
- root/octoprint/octoprint/config.yaml
- creates `/octoprint/octoprint` and `/octoprint/plugins` folders explicitly during docker build
- starts octoprint service using `--basedir /octoprint/octoprint` instead of just `/octoprint`
- changes the recommended mount path for the `config-editor` container to `octoprint:/octoprint`
- updates the example and test compose files and README instructions to reflect this change
**BREAKING CHANGES** This may be a breaking change for existing users that are using a volume mounting strategy other than the recommended strategy, thus will constitue a new major release for the image. 
Where before the root context of the volume mount looked like this:
```
/octoprint
├── config.backup
├── config.yaml
├── data
│   ├── announcements
│   ├── appkeys
│   ├── backup
│   ├── pluginmanager
│   ├── …
```
> Enable backup restore

- CHANGELOG.md
- Dockerfile
- README.md
- root/etc/cont-init.d/v3-dir-structure-check
- test/compose.test.yml
- closes #141 
- closes #138 
Instead of creating a migration strategy guide in the release docs, I went the route of detecting when a v3 container was being started with a v2 file structure, and then auto-migrate the file structures for them during container initialization.
This would potentially be a breaking release, in the event that two octoprint containers are using the same volume and the second container is added while the first (which is a v2 container) is running.
However, I've decided against classifying this as a breaking change (and thereby requiring a v4 release), because the current design of octoprint and octoprint in docker does not really support horizontal scaling due to the requirements to bind a host device.
> V3 image migration

- CONTRIBUTING.md
- README.md
- docs/building-an-octoprint-image.md
creates skeleton for `CONTRIBUTING.md` and a `docs` folder for more expansive user instructions. 
related to #145 and #144
> add skeletons for CONTRIBUTING and docs

- root/etc/services.d/octoprint/run
fixes #160 
Sets `--port 5000` in the octoprint service run script so that inadvertently setting `OCTOPRINT_PORT` doesn't break the haproxy integration.
> add port to init script

- Dockerfile
- README.md
See #164 
**I haven't tested this**, just made the PR because I felt like being nice. If there are extra changes that need to happen, I'll happily leave and take my limited docker knowledge away, you won't miss much.
> Remove `-y` from default mjpg streamer params

- README.md
Add the `s6-svc` restart command referenced in this issue https://github.com/OctoPrint/octoprint-docker/issues/90#issuecomment-743775659
Fix broken 'building the image yourself' link
> Add octoprint restart command to readme and link fix

- root/etc/haproxy/haproxy.cfg
Recent changes to Docker have made it so exposed ports that are bound to IPv6 will only forward to the IPv6 container address. This now requires the code in the container to listen on IPv6.
The "v4v6" part ensures that HAProxy will also listen on IPv4, regardless of system/container config.
> Listen on both IPv4 and IPv6.

- docker-compose.yml
The device listed was not right for my printer. using the command allowed me to list them and then pug in my printer and rerun to find the correct name
> adds command to discover usb device name

- docker-compose.yml
It took me a little bit to figure out how to run
```sh
python -m serial.tools.miniterm
```
and based on the question [here](https://github.com/OctoPrint/octoprint-docker/discussions/212), I wasn't the only one, so just a little hint on how to be able to run the command
> add a note that pyserial is needed for miniterm

- Dockerfile
Facilitate plugin support of libusb, libudev and hid devices
Such as https://plugins.octoprint.org/plugins/usbrelaycontrol/ - it fails to install in Octoprint docker without the above packages
Related issue at https://github.com/abudden/OctoPrint-USBRelayControl/issues/1#issuecomment-1057791175
> Include libusb-dev and libudev-dev

- Dockerfile
Necessary for H.265 encoding with ffmpeg. See #226
> Add x265 to image

- docker-compose.yml
GUID is not a valid envvar in our (code-server) container, it should be PGID. As a side note, while this MAY work fine, we don't support a PUID/PGID of 0.
> correct GUID typo on the code-server compose section

- Dockerfile
- root/etc/haproxy/haproxy.cfg
By changing the docker version from 3.8 to 3.10-slim-bullseye, it seems to fix #259.
This also updates the haproxy.cfg to the latest version requirements as there have been some changes there as well for the config. 
In the docker logs there are still issues around webcam endpoints.
2023-06-01 00:10:48,907 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
> Fixes for 1.9 - Babel app not found

- root/etc/haproxy/haproxy.cfg
HTTP2 nowadays is a must have feature to improve the speed of the webservices.
> Enable HTTP/2 protocol by default in HaProxy

- minimal/Dockerfile
My Raspberry Pi 1 is slow and with different `octoprint_ref` value, it takes an hour to redo the `apt-get` step. Moving the `ARG` further down, right before where it is used, makes caching more effective.
> Allow the `apt-get` steps to be cached when rebuilding with different `octoprint_ref` build argument.

- .github/workflows/build.yml
- .github/workflows/octoprint-release.yml
actions/cache{v1|v2} will cease functioning on Feb 1st, see https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
> chore: update deprecated github actions

- root/etc/cont-init.d/v3-dir-structure-check
Fixed spelling on line 6:
was:
echo "AUTOMIGATE enabled...."
now:
echo "AUTOMIGRATE enabled...."
> Update v3-dir-structure-check (fixed spelling error)

- README.md
Updating docs to use correct Settings locations for `Stream URL` and `Snapshot URL`.
> Webcam setup doc tweak
