OctoPrint/octoprint-docker

- Dockerfile
#2 
Please review and confirm that fix is working.
> Fix an issue with pip command

- Dockerfile
- docker-compose.yml
> Add octoprint user to groups

- .github/workflows/build-latest.yml
- .github/workflows/deploy-latest.yml
- .github/workflows/dockerimage.yml
- .github/workflows/latest.yml
- Makefile
> Multi arch build

- Dockerfile
> amend PATH to include ffmpeg and cura

- .github/workflows/build-latest.yml
- .github/workflows/deploy-latest.yml
general maintenance, just updates the buildx action.
> Update buildx action

- .github/workflows/octoprint-release.yml
just setting the default using proper case since we support overrides
> no need to coerce if overrides supported

- .github/workflows/build.yml
- .github/workflows/octoprint-release.yml
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
> Add octoprint back to base image

- Dockerfile
> Maintenance s6 overlay update

- .github/workflows/octoprint-release.yml
fixes typo of `displatch` to `dispatch`
> fix typo in release workflow

- .github/workflows/octoprint-release.yml
> Fix insufficient scope release workflow error

- .github/workflows/octoprint-release.yml
no reason to run push filters if the event is not a push!
> add condition to push_filters job

- .github/filters.yml
- .github/workflows/dockerhub-description.yml
> Update docker hub docs workflow

- .github/workflows/dockerhub-description.yml
fixes 'filter not found error'
> add actions/checkout@v2

- docs/building-an-octoprint-image.md
The URL was incorrect .. it was https://https://.....
(Sorry, I changed the name of my branch after and seems it closed the original PR)
> Fixed a typo in the URL to the video

- .github/workflows/build.yml
- .github/workflows/octoprint-release.yml
- Makefile
- README.md
- docs/using_the_minimal_image.md
- minimal/Dockerfile
- minimal/config.yaml
- minimal/docker-entrypoint.sh
> Distribute minimal image

- README.md
> add supported platforms to docs

- Dockerfile
- minimal/Dockerfile
These are my initial works over this repos images, tried to don't make huge updates for sanity reasons.
- main's image down to roughly **740 Mb**
- minimal's image down to roughly **630 Mb**
Looks like **ffmpeg** needs a lot of dependencies. There are futher improvements that could be commited.
Tested on ``arm64`` and ``amd64``
> works on issue #154

- Dockerfile
- minimal/Dockerfile
Reverts OctoPrint/octoprint-docker#173
> Revert "works on issue #154"

- root/etc/haproxy/haproxy.cfg
Reverts OctoPrint/octoprint-docker#175
> Revert "Listen on both IPv4 and IPv6."

- minimal/Dockerfile
companion PR for https://github.com/OctoPrint/octoprint-docker/pull/236
> add libffi-dev to minimal

- README.md
- root/etc/services.d/mjpg-streamer/run
- Add support for multiple webcam devices.
- Fix broken README links and minor markdown linting errors.
Fixes #244
> feat: add support for multiple cameras

- root/etc/services.d/mjpg-streamer/run
fixed camera port, start from port 8080
> fix: fixed camera port

- root/etc/services.d/mjpg-streamer/run
> revert #245
